apiVersion: v1
kind: ConfigMap
metadata:
  name: hareta-backend  # Change this to your desired ConfigMap name
data:
  AWS_BUCKET: "hareta-bucket"
  AWS_DOMAIN: "d2csq352pki9k7.cloudfront.net"
  AWS_REGION: "ap-southeast-1"
  GIN_MODE: "release"
  JWT_SECRET_KEY: "giahanismylover"
  MAIL_PORT: "587"
  MYSQL_GORM_DB_URI: "root:0E123W9h1234g46>@tcp(127.0.0.1:3306)/hareta?charset=utf8mb4&parseTime=True&loc=Local"
  RABBITMQ_URL: "amqps://piatbmdg:qoKp8pJxnWbCdF_yo2YwdmyLNIedlvJE@armadillo.rmq.cloudamqp.com/piatbmdg"
  REDIS_GO_REDIS_URI: "redis://:ngogiahan7203@127.0.0.1:6379/0"
