apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: hareta-backend
spec:
  host: hareta
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
  - name: v1
    labels:
      version: v1
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hareta
spec:
  hosts:
    - "api.hareta.online"
  gateways:
    - reversed-gateway
  http:
    - match:
      - uri:
          prefix: /
      route:
        - destination:
            host: hareta
            port:
              number: 3000
