name: 'Dev Deployment'

on:
  push:
    branches:
      - main

env:
  NAME: blox3-v1-prod
  ZONE: asia-southeast1-a

jobs:
  build-deploy:
    name: Build and deploy application to EKS
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker
        run: |
          docker build -t toan3082004/hareta:latest .

      - name: Upload to Registry
        run: |
          docker push toan3082004/hareta:latest
